x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  ibis:
    image: nutomic/ibis:0.3.0
    ports:
      - "3000:3000"
    restart: always
    logging: *default-logging
    environment:
      - LEPTOS_SITE_ADDR=0.0.0.0:3000
