x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  ibis:
    image: nutomic/ibis:0.3.0
    ports:
      - "3000:3000"
    restart: always
    logging: *default-logging
    environment:
      - LEPTOS_SITE_ADDR=0.0.0.0:3000
    volumes:
      - type: bind
        source: ./config.toml
        target: /config.toml
    depends_on:
      - postgres

  postgres:
    image: docker.io/pgautoupgrade/pgautoupgrade:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=ibis
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ibis
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
        is_directory: true
    logging: *default-logging

  postfix:
    image: docker.io/mwader/postfix-relay
    restart: always
    logging: *default-logging
